// SPDX-License-Identifier: GPL-3.0-or-later

//! Sync-daemon supervisor integration: systemd user unit on Linux.
//! See [ADR-0020](../../../../doc/adr/0020-daemon-service-supervision.md)
//! (the launchd half is superseded by
//! [ADR-0028](../../../../doc/adr/0028-drop-macos-support.md)).
//!
//! The unit body has the running binary's absolute path baked in at
//! `install` time (`std::env::current_exe()`), so a later `bypass`
//! upgrade that changes the install path requires re-running
//! `bypass sync daemon install` — mirrored in the function's
//! docstring.

#![cfg(unix)]

use std::path::{Path, PathBuf};
use std::process::Command;

use anyhow::{Context, Result};

// ----- public surface --------------------------------------------------

/// Write the systemd user unit to the conventional path. Idempotent
/// — overwrites any existing `bypass`-owned file. Runs `systemctl
/// --user daemon-reload` so the new unit is picked up.
pub fn install() -> Result<u8> {
    let exe = current_exe()?;
    let path = unit_path()?;
    let body = render_unit(&exe);
    write_unit_file(&path, &body)?;
    reload_supervisor()?;
    eprintln!("bypass-sync: wrote {}", path.display());
    eprintln!(
        "bypass-sync: enable autostart with `bypass sync daemon enable`, \
         or run once with `bypass sync daemon start`"
    );
    Ok(0)
}

/// Remove the systemd unit installed by [`install`]. Best effort: if
/// the file isn't there, says so but exits 0. Always runs
/// `daemon-reload` afterwards.
pub fn uninstall() -> Result<u8> {
    let path = unit_path()?;
    match std::fs::remove_file(&path) {
        Ok(()) => eprintln!("bypass-sync: removed {}", path.display()),
        Err(e) if e.kind() == std::io::ErrorKind::NotFound => {
            eprintln!(
                "bypass-sync: {} was not present; nothing to remove",
                path.display()
            );
        }
        Err(source) => {
            return Err(anyhow::Error::from(source).context(format!("remove {}", path.display())));
        }
    }
    reload_supervisor()?;
    Ok(0)
}

/// Ask systemd to start the daemon now (not boot-persistent unless
/// `enable` was also run).
pub fn start() -> Result<u8> {
    supervisor_op(SupervisorOp::Start)
}

pub fn stop() -> Result<u8> {
    supervisor_op(SupervisorOp::Stop)
}

pub fn enable() -> Result<u8> {
    supervisor_op(SupervisorOp::Enable)
}

pub fn disable() -> Result<u8> {
    supervisor_op(SupervisorOp::Disable)
}

/// Surface the supervisor's view of the daemon. Distinct from
/// [`super::socket::query_status`] — see ADR-0020:
///
/// - `bypass sync daemon status`: is the supervisor running it?
/// - `bypass sync status`: what does the running daemon see?
pub fn status() -> Result<u8> {
    supervisor_op(SupervisorOp::Status)
}

// ----- supervisor calls -----------------------------------------------

enum SupervisorOp {
    Start,
    Stop,
    Enable,
    Disable,
    Status,
}

fn supervisor_op(op: SupervisorOp) -> Result<u8> {
    let verb = match op {
        SupervisorOp::Start => "start",
        SupervisorOp::Stop => "stop",
        SupervisorOp::Enable => "enable",
        SupervisorOp::Disable => "disable",
        SupervisorOp::Status => "status",
    };
    let status = Command::new("systemctl")
        .args(["--user", verb, "bypass-sync.service"])
        .status()
        .context("spawn `systemctl --user`")?;
    Ok(u8::try_from(status.code().unwrap_or(1)).unwrap_or(1))
}

fn reload_supervisor() -> Result<()> {
    let status = Command::new("systemctl")
        .args(["--user", "daemon-reload"])
        .status()
        .context("spawn `systemctl --user daemon-reload`")?;
    if !status.success() {
        anyhow::bail!(
            "`systemctl --user daemon-reload` failed (exit {})",
            status.code().unwrap_or(-1)
        );
    }
    Ok(())
}

// ----- path / template helpers -----------------------------------------

fn unit_path() -> Result<PathBuf> {
    let home = dirs::home_dir().context("cannot resolve $HOME; set the variable manually")?;
    Ok(home.join(".config/systemd/user/bypass-sync.service"))
}

fn current_exe() -> Result<PathBuf> {
    std::env::current_exe().context("resolve current `bypass` binary path for service install")
}

fn write_unit_file(path: &Path, body: &str) -> Result<()> {
    if let Some(parent) = path.parent() {
        std::fs::create_dir_all(parent)
            .with_context(|| format!("create directory {}", parent.display()))?;
    }
    std::fs::write(path, body).with_context(|| format!("write {}", path.display()))?;
    Ok(())
}

// ----- unit template ---------------------------------------------------

fn render_unit(exe: &Path) -> String {
    format!(
        "# SPDX-License-Identifier: GPL-3.0-or-later\n\
         # Auto-generated by `bypass sync daemon install` (ADR-0020).\n\
         # Re-run that command after upgrading `bypass` so the path\n\
         # below stays in sync with the actual binary.\n\
         [Unit]\n\
         Description=bypass-sync LAN peer-to-peer sync daemon\n\
         Documentation=https://github.com/hiroshiyui/bypass\n\
         After=network-online.target\n\
         \n\
         [Service]\n\
         Type=simple\n\
         ExecStart={exe} sync daemon\n\
         Restart=on-failure\n\
         RestartSec=10\n\
         Environment=RUST_LOG=warn\n\
         \n\
         [Install]\n\
         WantedBy=default.target\n",
        exe = exe.display(),
    )
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn rendered_systemd_unit_has_bin_path_and_restart_directive() {
        let body = render_unit(Path::new("/opt/bypass/bin/bypass"));
        assert!(body.contains("ExecStart=/opt/bypass/bin/bypass sync daemon"));
        assert!(body.contains("Restart=on-failure"));
        assert!(body.contains("[Install]\nWantedBy=default.target"));
        assert!(body.starts_with("# SPDX-License-Identifier:"));
    }

    #[test]
    fn unit_path_lives_under_xdg_systemd_user() {
        // We can't assert the exact path without HOME, but the suffix
        // should match the ADR-0020 conventional location.
        let p = unit_path().unwrap();
        assert!(
            p.ends_with(".config/systemd/user/bypass-sync.service"),
            "got {}",
            p.display()
        );
    }
}
